// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;

      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyAdZrLQYOItCnG4NmsZRdEDsqWirktypIQ",
      authDomain: "login-auth-85db4.firebaseapp.com",
      projectId: "login-auth-85db4",
      storageBucket: "login-auth-85db4.appspot.com",
      messagingSenderId: "786120057253",
      appId: "1:786120057253:web:49e10d2599552681dd884c");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyhMJrvEx34vb_dgBiAEjavj23XyQvK7Q',
    appId: '1:786120057253:android:b8c6a3fa1c1dc315dd884c',
    messagingSenderId: '786120057253',
    projectId: 'login-auth-85db4',
    storageBucket: 'login-auth-85db4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSXaTNMUX8Sop8VwYyTVdvZQ6LFHXcRD0',
    appId: '1:786120057253:ios:7615472e02444703dd884c',
    messagingSenderId: '786120057253',
    projectId: 'login-auth-85db4',
    storageBucket: 'login-auth-85db4.appspot.com',
    iosBundleId: 'com.example.logInAuth',
  );
}
